#' Default trajectory templates (12-template catalog, v0.4.0)
#'
#' Built-in 12 hypothesis-driven trajectory templates used by
#' `classify_trajectory()` and `score_trajectory()`:
#' Early × 4 (Burst_Up, Loss_Down, Peak, Trough) + Mid × 4
#' (Plateau_Up, Plateau_Down, Peak, Trough) + Late × 2 (Burst_Up,
#' Loss_Down) + Monotonic × 2 (Up, Down). The atlas surface
#' (`pdactrace_reference$rna_pattern`) restricts visible best-match
#' calls to Early × 4 only — non-Early calls are flagged via
#' `excluded_*_pattern` columns. See `?early_pattern_names`,
#' `?mid_pattern_names_excluded` for membership lists.
#'
#' @format A named list of length 12, each element a numeric vector
#'   of length 4 (z-scored expected values across stages
#'   Normal / Early / Mid / Late).
#' @keywords datasets
"default_templates"

#' Atlas metadata
#'
#' Version, snapshot, source-script, and build metadata for the bundled
#' pdactrace reference atlas.
#'
#' @format A named list.
#' @keywords datasets
"atlas_metadata"

#' Random-effects meta-analysis table
#'
#' Cohort-level and random-effects meta-analysis summaries used to populate
#' v0.2.0 meta-analysis and tier columns in `pdactrace_reference`.
#'
#' @format A data.frame with one row per gene and meta-analysis summary
#'   columns.
#' @keywords datasets
"meta_analysis"

#' Synthetic RNA count matrix for runnable examples
#'
#' Tiny synthetic RNA-seq count matrix bundled so the user-cohort
#' workflow (`fit_stage_de` -> `classify_trajectory` ->
#' `assemble_user_evidence` -> `compute_audit_score`) can be exercised
#' end-to-end inside examples and the user-cohort vignette without an
#' external download. The first 10 rows (`TGENE01`-`TGENE10`) carry an
#' injected `Early_Burst_Up` signal (count lift of ~60-90 reads from
#' Stage I onward); the remaining 40 rows are negative-binomial noise.
#' Generated by `data-raw/build_toy_data.R` with `set.seed(2026)`.
#'
#' @format Integer matrix, 50 genes x 24 samples. Row names
#'   `TGENE01..TGENE50`; column names `S01..S24` matching
#'   `toy_coldata$sample`.
#' @keywords datasets
#' @examples
#' fit <- fit_stage_de(toy_counts,
#'                       stage  = toy_coldata$stage,
#'                       cohort = toy_coldata$cohort)
#' head(fit)
"toy_counts"

#' Synthetic stage / cohort metadata for runnable examples
#'
#' Sample-level metadata that pairs with `toy_counts` and
#' `toy_protein`. 24 samples balanced across the four canonical stages
#' and two synthetic cohorts.
#'
#' @format `data.frame` with 24 rows and 3 columns:
#'   * `sample` (character): `S01..S24`.
#'   * `stage`  (character): `"Normal"`, `"Early"`, `"Mid"`, `"Late"`,
#'     6 samples per stage.
#'   * `cohort` (character): `"CohortA"`, `"CohortB"`,
#'     12 samples per cohort.
#' @keywords datasets
"toy_coldata"

#' Public-data accession table backing list_data_sources()
#'
#' One row per public dataset that contributed to the v0.99.x
#' pdactrace reference atlas, covering bulk RNA-seq, tissue
#' proteomics, single-cell RNA, serum proteomics, pancreatitis
#' context, and validation cohorts. Backs the [list_data_sources()]
#' helper and is the source-of-truth for the manuscript's
#' data-availability section.
#'
#' @format `data.table` with one row per accession and columns
#'   `accession`, `layer`, `source_type`, `used_for`, `citation`,
#'   `url`. Generated by `data-raw/build_data_sources.R`.
#' @keywords datasets
"pdactrace_data_sources"

#' Synthetic tissue-protein log2 intensity matrix for runnable examples
#'
#' Tiny synthetic protein intensity matrix paired with `toy_counts` /
#' `toy_coldata`. The first 8 rows (`TPROT01`-`TPROT08`) carry an
#' injected `Early_Burst_Up` shape (log2 lift of ~0.6-1.0 from
#' Stage I); the remaining 42 rows are Gaussian noise around 12.
#' Generated by `data-raw/build_toy_data.R` with `set.seed(2026)`.
#'
#' @format Numeric matrix (log2 intensity), 50 proteins x 24 samples.
#'   Row names `TPROT01..TPROT50`; column names `S01..S24`.
#' @keywords datasets
"toy_protein"
